import csv
from pathlib import Path


class AnalysisService:
    """Reads generated analysis CSV files and shapes them for the mobile API."""

    def __init__(self, project_root):
        self.project_root = Path(project_root)
        self.output_dir = self.project_root / "analysis_outputs"

    def analysis_for_game(self, game):
        # Each analysis chart in the app comes from a separate CSV generated by
        # scripts/auto_pipeline.py.
        frequency = [
            {
                "number": int(row["numbers"]),
                "frequency": int(row["frequency"]),
            }
            for row in self._read_csv("number_frequency_by_game.csv")
            if row["lotto_game"] == game
        ]
        patterns = [
            {
                "pattern": row["odd_even_pattern"],
                "draws": int(row["draws"]),
            }
            for row in self._read_csv("odd_even_patterns_by_game.csv")
            if row["lotto_game"] == game
        ]
        sum_rows = [
            row for row in self._read_csv("sum_statistics_by_game.csv")
            if row["lotto_game"] == game
        ]

        if not frequency and not patterns and not sum_rows:
            # Return an empty analysis object instead of a 404 so the app can
            # show an empty detail screen for new or incomplete games.
            return {
                "lotto_game": game,
                "number_frequency": [],
                "odd_even_patterns": [],
                "sum_statistics": None,
            }

        return {
            "lotto_game": game,
            "number_frequency": frequency,
            "odd_even_patterns": patterns,
            "sum_statistics": self._normalize_sum_stats(sum_rows[0]) if sum_rows else None,
        }

    def list_suggestions(self):
        # CSV values may be written as floats, so normalize them to whole-number
        # values before sending JSON to Swift.
        return [
            {
                "lotto_game": row["lotto_game"],
                "suggested_combination": row["suggested_combination"],
                "sum": int(float(row["sum"])),
                "odd_even_pattern": row["odd_even_pattern"],
                "historical_frequency_score": int(float(row["historical_frequency_score"])),
                "basis": row["basis"],
            }
            for row in self._read_csv("possible_winning_numbers_by_game.csv")
        ]

    def ultra_lotto_trend_data(self):
        """Return the focused Ultra Lotto reports used by the mobile Trends tab."""
        patterns = [
            {
                "rank": int(row["rank"]),
                "pattern": row["odd_even_pattern"],
                "draws": int(row["draws"]),
                "draw_percentage": float(row["draw_percentage"]),
                "moving_window_days": int(row["moving_window_days"]),
                "moving_window_start": row["moving_window_start"],
                "moving_window_end": row["moving_window_end"],
                "moving_window_draws": int(row["moving_window_draws"]),
            }
            for row in self._read_optional_csv("ultra_lotto_6_58_recent_odd_even_patterns.csv")
        ]
        suggestions = [
            {
                "rank": int(row["rank"]),
                "suggested_combination": row["suggested_combination"],
                "odd_count": int(row["odd_count"]),
                "even_count": int(row["even_count"]),
                "sum": int(float(row["sum"])),
                "trend_score": float(row["trend_score"]),
                "matches_recent_sum_range": row["matches_recent_sum_range"].lower() == "true",
                "basis": row["basis"],
            }
            for row in self._read_optional_csv("ultra_lotto_6_58_trend_suggestions.csv")
        ]
        return {"odd_even_patterns": patterns, "suggestions": suggestions}

    def _read_csv(self, filename):
        # A missing generated file usually means the pipeline has not run yet.
        path = self.output_dir / filename
        if not path.exists():
            raise FileNotFoundError(f"Missing analysis file: {path}")
        with path.open(newline="", encoding="utf-8") as file:
            return list(csv.DictReader(file))

    def _read_optional_csv(self, filename):
        # The app can still load an older published snapshot while the next
        # pipeline run creates these newer focused-report files.
        path = self.output_dir / filename
        if not path.exists():
            return []
        with path.open(newline="", encoding="utf-8") as file:
            return list(csv.DictReader(file))

    def _normalize_sum_stats(self, row):
        # Convert string CSV values into numeric JSON values for charts/details.
        return {
            "count": int(float(row["count"])),
            "min": float(row["min"]),
            "median": float(row["median"]),
            "mean": float(row["mean"]),
            "max": float(row["max"]),
            "std": float(row["std"]),
        }
